name: dartantic_ai
description: >
  Dartantic is an agentic framework designed to make building client and
  server-side apps in Dart with generative AI easier and more fun!
version: 2.2.1
repository: https://github.com/csells/dartantic_ai
homepage: https://docs.dartantic.ai
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  anthropic_sdk_dart: ^0.3.1
  collection: ^1.19.1
  dartantic_interface: ^2.0.0
  google_cloud_ai_generativelanguage_v1beta: ^0.3.0
  google_cloud_protobuf: ^0.3.0
  html: ^0.15.6
  http: ^1.6.0
  json_schema: ^5.2.2
  logging: ^1.3.0
  mcp_dart: ^1.2.0
  meta: ^1.17.0
  mime: ^2.0.0
  mistralai_dart: ^0.1.1+1
  ollama_dart: ^0.3.0+1
  openai_core: ^0.10.2
  openai_dart: ^0.6.2
  rxdart: ^0.28.0
  sse_channel: ^0.2.2
  uuid: ^4.5.2

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  test: ^1.28.0
