name: example
description: Examples using dartantic_ai.
publish_to: none
resolution: workspace

environment:
  sdk: ^3.10.0

dependencies:
  chrono_dart: ^2.0.2
  cross_file: ^0.3.5+1
  dartantic_ai: ^2.2.1
  dartantic_interface: ^2.0.0
  dotprompt_dart: ^0.5.0
  freezed_annotation: ^3.1.0
  http: ^1.6.0
  json_annotation: ^4.9.0
  json_schema: ^5.2.2
  logging: ^1.3.0
  openai_core: ^0.10.2
  soti_schema_plus: ^1.3.0

dev_dependencies:
  all_lint_rules_community: ^0.0.43
  build_runner: ^2.10.4
  json_serializable: ^6.11.2
