name: dartantic_chat_example
description: >-
  Sample apps showing off various features of Dartantic Chat.
publish_to: none
version: 1.0.0+1
resolution: workspace

environment:
  sdk: ^3.7.0
  flutter: '>=3.27.0-0'

dependencies:
  flutter:
    sdk: flutter
  dartantic_chat:
    path: ..
  cupertino_icons: ^1.0.8
  shared_preferences: ^2.5.4
  url_launcher: ^6.3.2
  go_router: ^17.0.1
  uuid: ^4.5.2
  path: ^1.9.1
  path_provider: ^2.1.5
  flutter_markdown_plus: ^1.0.7
  google_fonts: ^6.3.3
  future_builder_ex: ^5.0.0
  split_view: ^3.2.1
  dartantic_ai: ^2.2.1
  cross_file: ^0.3.5+1
  json_schema: ^5.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/recipes_default.json
    - assets/halloween-bg.png
